#! /bin/sh

sxhkd &
panel &
dunst &
compton -f -D 3 &

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a google-chrome desktop='Web' focus=on
bspc rule -a teams desktop='Chat' state=floating
# bspc rule -a Screenkey manage=off
# bspc rule -a Gimp desktop='^8' state=floating follow=on
