version: "2.1"
services:
    transmission-openvpn:
        volumes:
            - ${MEDIA_FOLDER}/downloads/:/data
            - /etc/localtime:/etc/localtime:ro
            - /etc/openvpn/expressvpn/:/etc/openvpn/custom/
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=CUSTOM
            - OPENVPN_USERNAME=${OVPN_USERNAME}
            - OPENVPN_PASSWORD=${OVPN_PASSWORD}
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=192.168.0.0/16
            - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
            - DNS=8.8.8.8,8.8.4.4
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 9091:9091
            - 9117:9117
            - 7878:7878
            - 8989:8989
        restart: always
        image: haugene/transmission-openvpn
    jackett:
        image: linuxserver/jackett
        container_name: jackett
        network_mode: "service:transmission-openvpn"
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - AUTO_UPDATE=true #optional
            - RUN_OPTS=#optional
        volumes:
            - ${MEDIA_FOLDER}/appdata/jackett:/config
            - ${MEDIA_FOLDER}/downloads/watch:/downloads
        restart: unless-stopped
    radarr:
        image: linuxserver/radarr
        network_mode: "service:transmission-openvpn"
        container_name: radarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK_SET=022 #optional
        volumes:
            - ${MEDIA_FOLDER}/appdata/radarr:/config
            - ${MEDIA_FOLDER}/movies:/movies
            - ${MEDIA_FOLDER}/downloads/completed:/downloads
        restart: unless-stopped
    sonarr:
        image: linuxserver/sonarr
        network_mode: "service:transmission-openvpn"
        container_name: sonarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK_SET=022 #optional
        volumes:
            - ${MEDIA_FOLDER}/appdata/sonarr:/config
            - ${MEDIA_FOLDER}/tv_shows:/tv
            - ${MEDIA_FOLDER}/downloads/completed:/downloads
        restart: unless-stopped
    plex:
        image: linuxserver/plex
        container_name: plex
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - VERSION=docker
            - UMASK_SET=022 #optional
            - PLEX_CLAIM= #optional
        volumes:
            - /path/to/library:/config
            - ${MEDIA_FOLDER}/tv_shows:/tv
            - ${MEDIA_FOLDER}/movies:/movies
        restart: unless-stopped
